[project]
name = "meducate-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.1",
    "fastmcp>=2.13.0.2",
    "openai>=2.7.2",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.38.0",
]
